server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html/browser;

    # ── Angular app ───────────────────────────────────────────────────
    location / {
        try_files $uri $uri/ /index.html;
    }

    # ── Proxy das APIs para os backends ──────────────────────────────
    location /api/v1/usuarios {
        proxy_pass http://api-usuarios:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/tasks {
        proxy_pass http://api-pedidos:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/v1/vistos {
        proxy_pass http://api-vistos:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/v1/agencias {
        proxy_pass http://api-agencias:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
