spring.application.name=api-agencias



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.url=jdbc:postgresql://localhost:5432/agencias_db
spring.datasource.username=admin
spring.datasource.password=admin_password

jwt.secretkey=${JWT_SECRET_KEY}




cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
