spring.application.name=apidePedidos
server.port=8081


spring.datasource.url=jdbc:postgresql://postgres-pedidos:5432/pedidos_db
spring.datasource.username=postgres
spring.datasource.password=adminpass
spring.datasource.driver-class-name=org.postgresql.Driver


logs.datasource.url=jdbc:postgresql://postgres-logs:5432/logs_db
logs.datasource.username=postgres
logs.datasource.password=adminpass
logs.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.schema_update.unique_constraint_strategy=RECREATE_QUIETLY
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.security.oauth2.resourceserver.jwt.secret-key=${JWT_SECRET_KEY_BASE64}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
