spring.application.name=apidePedidos

server.port=8080

spring.data.mongodb.uri=mongodb://user:userpass@kanban-mongo-db:27017/pedidosdb?authSource=admin


mongodb.logs.uri=mongodb://user:userpass@kanban-mongo-db:27018/logsdb?authSource=admin


spring.security.oauth2.resourceserver.jwt.secret-key=YmJkZDQwOTAtN2M3Yy00NDBiLTk1ZjEtZGFkNjVhMWNiMmRh
